version: '3.4'

volumes:
  django-gen:
  django-socket:
  postgres-data:
  postgres-socket:

services:
  django:
    build: "."
    environment:
      - DJANGO_DEBUG
      - DJANGO_PUBLIC_HOSTNAME
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - "./django:/usr/src/django"
      - "django-socket:/var/www/uwsgi"
      - "django-gen:/gen"
      - "postgres-socket:/var/run/postgresql"

  nginx:
    image: nginx:1.25
    ports:
      - "${LISTEN_NGINX_HTTP}:80"
    restart: unless-stopped
    volumes:
      - "django-gen:/var/www/static:ro"
      - "django-socket:/var/www/uwsgi"
      - "./nginx/${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro"

  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "postgres-socket:/var/run/postgresql"
      - "./postgres_files:/postgres_files"
